<a href="https://colab.research.google.com/github/Qismeeee/AIO-Homework/blob/master/Numpy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.arange(0,10)
print(arr[arr%2==1])

[1 3 5 7 9]


In [ ]:
import numpy as np
arr = np.arange(0,10)
arr[arr%2==1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
import numpy as np
arr = np.arange(10)
arr2d = arr.reshape(2, -1)
print(arr2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
import numpy as np
arr1 = np.arange(10).reshape (2 , -1)
arr2 = np.repeat(1 ,10).reshape (2 , -1)
c = np.concatenate([ arr1 , arr2 ] , axis = 0)
print (" Result : \n", c )

 Result : 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
import numpy as np
arr1 = np.arange(10).reshape (2 , -1)
arr2 = np.repeat(1 ,10).reshape (2 , -1)
c = np.concatenate([ arr1 , arr2 ] , axis = 1)
print (" Result : \n", c )

 Result : 
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [ ]:
import numpy as np
arr = np.array ([1 ,2 ,3])
print( np.repeat( arr,3) )
print( np.tile(arr,3) )

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [ ]:
import numpy as np
a = np.array ([2 ,6 ,1 ,9 ,10 ,3 ,27])
index = np.where ((a >=5) &(a <=10) )
print ("result ", a [index])

result  [ 6  9 10]


In [ ]:
import numpy as np
def maxx (x , y ) :
  if x >= y :
    return x
  else :
    return y

a = np.array ([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np.array ([6 ,3 ,4 ,8 ,9 ,7 ,1])
pair_max = np.vectorize ( maxx , otypes =[ float ])
print( pair_max (a , b ) )

[6. 7. 9. 8. 9. 7. 5.]


In [ ]:
a = np.array ([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np.array ([6 ,3 ,4 ,8 ,9 ,7 ,1])

print ("Result ", np.where (a <b , b , a ) )

Result  [6 7 9 8 9 7 5]


In [ ]:
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 44.3MB/s]


In [ ]:
import matplotlib.image as mpimg
import numpy as np

# Đọc ảnh
img = mpimg.imread('/content/dog.jpeg')

# Chuyển ảnh màu sang ảnh xám dựa vào phương pháp Lightness
# Lightness method: gray = (max(R, G, B) + min(R, G, B)) / 2
gray_img_01 = np.mean(np.stack([img.max(axis=2), img.min(axis=2)]), axis=0)

# Hiển thị giá trị tại vị trí (0, 0)
gray_img_01[0, 0]

102.5

In [ ]:
# Download image
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib.image as mpimg
import numpy as np

# Đọc ảnh
img = mpimg.imread('/content/dog.jpeg')

# Chuyển ảnh màu sang ảnh xám dựa vào phương pháp Average
# Average method: gray = (R + G + B) / 3
gray_img_02 = np.mean(img, axis=2)

# Hiển thị giá trị tại vị trí (0, 0)
gray_img_02[0, 0]


Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 50.7MB/s]


107.66666666666667

In [ ]:
# Download image
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib.image as mpimg
import numpy as np

# Đọc ảnh
img = mpimg.imread('/content/dog.jpeg')

# Chuyển ảnh màu sang ảnh xám dựa vào phương pháp Luminosity
# Luminosity method: gray = 0.21 * R + 0.72 * G + 0.07 * B
gray_img_03 = 0.21 * img[:, :, 0] + 0.72 * img[:, :, 1] + 0.07 * img[:, :, 2]

# Hiển thị giá trị tại vị trí (0, 0)
gray_img_03[0, 0]


Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 63.2MB/s]


126.22999999999999

In [ ]:
# Download data
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

import pandas as pd
df = pd.read_csv('/content/advertising.csv')

# Lấy giá trị lớn nhất và chỉ mục tương ứng của nó trên cột Sales
max_sales_value = df['Sales'].max()
max_sales_index = df['Sales'].idxmax()

max_sales_value, max_sales_index


Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 9.06MB/s]


(27.0, 175)

In [ ]:
# Download data
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

import pandas as pd
df = pd.read_csv('/content/advertising.csv')

# Tính giá trị trung bình của cột TV
mean_tv = df['TV'].mean()

mean_tv


Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 13.9MB/s]


147.0425

In [ ]:
# Download data
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

import pandas as pd
df = pd.read_csv('/content/advertising.csv')

# Đếm số lượng bản ghi có giá trị tại cột Sales lớn hơn hoặc bằng 20
count_sales_ge_20 = (df['Sales'] >= 20).sum()

count_sales_ge_20


Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 14.5MB/s]


40

In [ ]:
# Download data
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

import pandas as pd
df = pd.read_csv('/content/advertising.csv')

# Lọc các bản ghi mà giá trị tại cột Sales lớn hơn hoặc bằng 15
filtered_df = df[df['Sales'] >= 15]

# Tính giá trị trung bình của cột Radio cho các bản ghi đã lọc
mean_radio = filtered_df['Radio'].mean()

mean_radio


Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 13.2MB/s]


26.22293577981651

In [ ]:
# Download data
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

import pandas as pd
df = pd.read_csv('/content/advertising.csv')

# Tính giá trị trung bình của cột Newspaper
mean_newspaper = df['Newspaper'].mean()

# Lọc các bản ghi mà giá trị tại cột Newspaper lớn hơn giá trị trung bình
filtered_df = df[df['Newspaper'] > mean_newspaper]

# Tính tổng các giá trị trong cột Sales cho các bản ghi đã lọc
total_sales = filtered_df['Sales'].sum()

total_sales


Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 13.7MB/s]


1405.1

In [ ]:
# Download data
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

import pandas as pd
df = pd.read_csv('/content/advertising.csv')

# Tính giá trị trung bình của cột Sales
A = df['Sales'].mean()

# Tạo mảng scores dựa trên điều kiện
scores = ['Good' if sale > A else 'Bad' if sale < A else 'Average' for sale in df['Sales']]

# In ra kết quả scores[7:10]
print(scores[7:10])


Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 14.3MB/s]
['Bad', 'Bad', 'Good']


In [ ]:
# Download data
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

import pandas as pd
import numpy as np

df = pd.read_csv('/content/advertising.csv')

# Tính giá trị trung bình của cột Sales
mean_sales = df['Sales'].mean()

# Tìm giá trị trong cột Sales gần nhất với giá trị trung bình
closest_to_mean = df['Sales'].iloc[(df['Sales'] - mean_sales).abs().argsort()[:1]].values[0]

# Tạo mảng scores dựa trên điều kiện
scores = ['Good' if sale > closest_to_mean else 'Bad' if sale < closest_to_mean else 'Average' for sale in df['Sales']]

# In ra kết quả scores[7:10]
print(scores[7:10])


Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 13.4MB/s]
['Bad', 'Bad', 'Good']
